## `loc and iloc`

- loc - label based indexing
- iloc - integer based indexing

In [35]:
import pandas as pd
df = pd.read_csv('2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv')
df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581)
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755)
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   X                                           3023 non-null   float64
 1   Y                                           3023 non-null   float64
 2   Unique Squirrel ID                          3023 non-null   object
 3   Hectare                                     3023 non-null   object
 4   Shift                                       3023 non-null   object
 5   Date                                        3023 non-null   int64
 6   Hectare Squirrel Number                     3023 non-null   int64
 7   Age                                         2902 non-null   object
 8   Primary Fur Color                           2968 non-null   object
 9   Highlight Fur Color                         1937 non-null   object
 10  Combination of Primary and Highlight Color  3023 non-null   object
 11  Color notes                                 182 non-null    object
 12  Location                                    2959 non-null   object
 13  Above Ground Sighter Measurement            2909 non-null   object
 14  Specific Location                           476 non-null    object
 15  Running                                     3023 non-null   bool
 16  Chasing                                     3023 non-null   bool
 17  Climbing                                    3023 non-null   bool
 18  Eating                                      3023 non-null   bool
 19  Foraging                                    3023 non-null   bool
 20  Other Activities                            437 non-null    object
 21  Kuks                                        3023 non-null   bool
 22  Quaas                                       3023 non-null   bool
 23  Moans                                       3023 non-null   bool
 24  Tail flags                                  3023 non-null   bool
 25  Tail twitches                               3023 non-null   bool
 26  Approaches                                  3023 non-null   bool
 27  Indifferent                                 3023 non-null   bool
 28  Runs from                                   3023 non-null   bool
 29  Other Interactions                          240 non-null    object
 30  Lat/Long                                    3023 non-null   object
dtypes: bool(13), float64(2), int64(2), object(14)
memory usage: 463.6+ KB

### `.loc` syntax: `df.loc[row_label,column_label]`

`.loc` is known as label-based indexing. 

You use it only when you want to use the name of the rows or columns in the `df`.

`row_label` refers to the index of the dataframe.

Therefore, if you want to get a specific row, you will refer to the index. In this case, the `df` has a numeric value

Here, For `row[0]`, which is the first row in the `df`, you will get all the column values:

In [24]:
df.loc[0]

X                                                                               -73.9561
Y                                                                                40.7941
Unique Squirrel ID                                                        37F-PM-1014-03
Hectare                                                                              37F
Shift                                                                                 PM
Date                                                                            10142018
Hectare Squirrel Number                                                                3
Age                                                                                  NaN
Primary Fur Color                                                                    NaN
Highlight Fur Color                                                                  NaN
Combination of Primary and Highlight Color                                             +
Color notes                                                                          NaN
Location                                                                             NaN
Above Ground Sighter Measurement                                                     NaN
Specific Location                                                                    NaN
Running                                                                            False
Chasing                                                                            False
Climbing                                                                           False
Eating                                                                             False
Foraging                                                                           False
Other Activities                                                                     NaN
Kuks                                                                               False
Quaas                                                                              False
Moans                                                                              False
Tail flags                                                                         False
Tail twitches                                                                      False
Approaches                                                                         False
Indifferent                                                                        False
Runs from                                                                          False
Other Interactions                                                                   NaN
Lat/Long                                      POINT (-73.9561344937861 40.7940823884086)
Name: 0, dtype: object

`df.loc[0]` will return a `Series` data type value

If you want mulitple rows, then:

In [28]:
df.loc[0:2]

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581)

In this case, `df.loc[0:2]` will return a `DataFrame`

Sometimes you can have `string indexes` in the `DataFrame`:

In [30]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["NY", "LA", "SF"]
}, index=["a", "b", "c"])

df

      name  age city
a    Alice   25   NY
b      Bob   30   LA
c  Charlie   35   SF

Here the `.loc` syntax will look like:

In [31]:
df.loc['a']

name    Alice
age        25
city       NY
Name: a, dtype: object

For string indexes, when you want to multiple rows, you have to use `,` to seperate the first and the last row you specify.

`:` is only for numerical indexes.

And, you have to enclose the rows in double brackets:

In [34]:
df.loc[['a','b']]

    name  age city
a  Alice   25   NY
b    Bob   30   LA

### Using `.loc` for rows and columns

In [40]:
#a specific row and column
df.loc[0,'Hectare']

'37F'

In [41]:
#multiple rows and a column
df.loc[0:2,'Hectare']

0    37F
1    37E
2    02E
Name: Hectare, dtype: object

In [42]:
#multiple rows and multiple columns
df.loc[0:2,['Age', 'Hectare']]

     Age Hectare
0    NaN     37F
1  Adult     37E
2  Adult     02E

### `.loc` syntax quirk

If you want to a specific column using '`.loc`, then you cannot leave the row argument blank. 

You always have to specify which rows you want for the specific column. 

If you want all the rows, then use `:`:

In [50]:
df.loc[:,'Age']

0            NaN
1          Adult
2          Adult
3       Juvenile
4            NaN
          ...
3018       Adult
3019       Adult
3020       Adult
3021         NaN
3022       Adult
Name: Age, Length: 3023, dtype: object

If you simply type: `df.loc['Age']`, python will assume the `Age` to be row label. You have to specify something in the row argument.

But it doesn't work that way for `rows`. When you want a particular row, you can leave the column argument blank. Pyhton will just return all the columns for that specific row, unless you specify which columns you want. 

This is an important quirk to remember.

### `iloc` syntax: `df.iloc[row_index(es), column_index(es)]

`iloc` refers to integer based indexing.

Here, you do not use the names of the rows and columns.

Instead, you refer to their positions in the `DataFrame`, i.e. 1st row, 5th column etc.

In [53]:
#single row
df.iloc[0]

X                                                                               -73.9561
Y                                                                                40.7941
Unique Squirrel ID                                                        37F-PM-1014-03
Hectare                                                                              37F
Shift                                                                                 PM
Date                                                                            10142018
Hectare Squirrel Number                                                                3
Age                                                                                  NaN
Primary Fur Color                                                                    NaN
Highlight Fur Color                                                                  NaN
Combination of Primary and Highlight Color                                             +
Color notes                                                                          NaN
Location                                                                             NaN
Above Ground Sighter Measurement                                                     NaN
Specific Location                                                                    NaN
Running                                                                            False
Chasing                                                                            False
Climbing                                                                           False
Eating                                                                             False
Foraging                                                                           False
Other Activities                                                                     NaN
Kuks                                                                               False
Quaas                                                                              False
Moans                                                                              False
Tail flags                                                                         False
Tail twitches                                                                      False
Approaches                                                                         False
Indifferent                                                                        False
Runs from                                                                          False
Other Interactions                                                                   NaN
Lat/Long                                      POINT (-73.9561344937861 40.7940823884086)
Name: 0, dtype: object

In [54]:
#multiple rows
df.iloc[0:2]

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)

In [55]:
#multiple rows and a single column
df.iloc[0:2,2]

0    37F-PM-1014-03
1    37E-PM-1006-03
Name: Unique Squirrel ID, dtype: object

In [56]:
#multiple rows and columns
df.iloc[0:2, 3:5]

  Hectare Shift
0     37F    PM
1     37E    PM

Just like in `.loc`, `.iloc` has the same quirk i.e. you cannot leave the row argument blank, when you are looking for a specific column. You need to specifiy something in the row argument.

### If you want just one particular value from the DataFrame, then you can use `.at` or `.iat`

In [57]:
df.at[0,'Shift']

'PM'

This is will return a `str` data type value, which you can use further down the line if you need to.

This is similar to:

In [62]:
df.loc[0,'Shift']

'PM'

The difference between `.at` and `.iat` is similar to `.loc` and `.iloc` i.e. label based indexing and integer based indexing