## List and Dictionary Comprehension

- is a short and sweet way to create lists and dictionaries
- instead of writing 3-4 lines for each loop, you can condense it into 1 line
- helps reduce the amount of code you write and also makes for much cleaner code

### How to create a list using List Comprehension

1. First write your `for loop`:
    - **for {variable_name} in {iterable}**
    
2. Then, work backward on what you want to with the varible:
     - **{variable operation}**

**For example:** If you want to create a new list that is the square of each number in an existing list:

    new_list = [num* num for num in list_of_numbers]
    
    for {variable_name} in {iterable} -> for num in list_of_numbers
    
    {variable operation} -> num * num

`Iterable` can be anything - list, dictionary, tuple etc. The above example is a list, but it can be any object that you can loop thru.

You can also add a condition to the list comprehension. Using the same example from above, suppose you want to only square the numbers > 10:

    new_list = [num * num for num in list_of_numbers if num > 5]

Your though process should be the same as when you're writing a ` for loop`:
    1. First, write the for statement.
    2. Then, the operation you want to perform on each value in the iterable.
    3. Set any conditions if required.

### Dictionary comprehension

Works like list comprehesion:
    
    new_dict = new_key:new_value for (key,value) in existing_dict.items() if **condition**

### Iterating thru a df using `df.iterrows()`

In [15]:
#creating a dict
student_dict = {
    "student": ["Angela", "James", "Lily"], 
    "score": [56, 76, 98]
}

#Looping through dictionaries:
for (key, value) in student_dict.items():
    #Access key and value
    print(key,value)

student ['Angela', 'James', 'Lily']
score [56, 76, 98]

In [16]:
#creating a df from the dict
import pandas as pd
student_data_frame = pd.DataFrame(student_dict)
student_data_frame

  student  score
0  Angela     56
1   James     76
2    Lily     98

In [17]:
#Loop through rows of a data frame using iterrows()
#iterrows returns (index,row) of the df which you can access seperately
for (index, row) in student_data_frame.iterrows():
    #Access index
    print(index)

0
1
2

In [4]:
#print each row
for (index, row) in student_data_frame.iterrows():
    print(row)

student    Angela
score          56
Name: 0, dtype: object
student    James
score         76
Name: 1, dtype: object
student    Lily
score        98
Name: 2, dtype: object

In [5]:
#accessing each column in the row
for (index, row) in student_data_frame.iterrows():
    print(row['student'])

Angela
James
Lily

## NATO Alphabet

In [6]:
# Keyword Method with iterrows()
# {new_key:new_value for (index, row) in df.iterrows()}

#TODO 1. Create a dictionary in this format:
{"A": "Alfa", "B": "Bravo"}

#TODO 2. Create a list of the phonetic code words from a word that the user inputs.

{'A': 'Alfa', 'B': 'Bravo'}

In [7]:
#creating a df from the csv file
df = pd.read_csv('nato_phonetic_alphabet.csv')
df.head()

  letter     code
0      A     Alfa
1      B    Bravo
2      C  Charlie
3      D    Delta
4      E     Echo

In [9]:
#creating a dictionary from the df using iterrows and dictionary comprehension
my_dict = {row.letter:row.code for(index,row) in df.iterrows()}
my_dict

{'A': 'Alfa',
 'B': 'Bravo',
 'C': 'Charlie',
 'D': 'Delta',
 'E': 'Echo',
 'F': 'Foxtrot',
 'G': 'Golf',
 'H': 'Hotel',
 'I': 'India',
 'J': 'Juliet',
 'K': 'Kilo',
 'L': 'Lima',
 'M': 'Mike',
 'N': 'November',
 'O': 'Oscar',
 'P': 'Papa',
 'Q': 'Quebec',
 'R': 'Romeo',
 'S': 'Sierra',
 'T': 'Tango',
 'U': 'Uniform',
 'V': 'Victor',
 'W': 'Whiskey',
 'X': 'X-ray',
 'Y': 'Yankee',
 'Z': 'Zulu'}

In [10]:
#getting input from the user
my_input = input('What is your name?\n')

What is your name?
rahul

In [11]:
#converting it into a list and all upper case to compare with keys in my_dict
my_input = list(my_input.upper())
my_input

['R', 'A', 'H', 'U', 'L']

In [12]:
#getting the phonetic 
phonetic_list = [my_dict[letter] for letter in my_input]
phonetic_list

['Romeo', 'Alfa', 'Hotel', 'Uniform', 'Lima']